name: build

on:
  repository_dispatch:
    types: [build-on-demand]
  workflow_dispatch:
    inputs:
      name:
        description: 'name'
        required: false
        type: string
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [node16]
        arch: [x64, arm64]
        os: [linux, macos, win]
    steps:
      - name: Setup
        run: |
          sudo apt update
          export DEBIAN_FRONTEND=noninteractive
          sudo apt -y install gnutls-bin git ca-certificates
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          repository: 'Zaarrg/TTVDropBot'
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Build
        run: |
          sed -i 's/await checkisClaimeable/\/\/await checkisClaimeable/g' src/Checks/pointsCheck.ts
          npm ci --production
          npm cache clean --force
          npm install
          npm run build
          export NODE_ENV=production
      - name: Package
        uses: lando/pkg-action@v2
        id: pkg
        with:
          entrypoint: ./build/index.js
          arch: ${{ matrix.arch }}
          node-version: ${{ matrix.node-version }}
          os: ${{ matrix.os }}
          options: -C GZip
          upload: false
      - name: Upload ${{ steps.pkg.outputs.artifact-key }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.pkg.outputs.artifact-key }}
          path: ${{ steps.pkg.outputs.file }}
