name: build

on:
  repository_dispatch:
    types: [build-on-demand]
  workflow_dispatch:
    inputs:
      name:
        description: 'name'
        required: false
        type: string
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x64
          - arm64
        node-version:
          - node16
        os:
          - linux
          - macos
          - win
    steps:
      - name: Setup
        run: |
          sudo apt update
          export DEBIAN_FRONTEND=noninteractive
          sudo apt -y install gnutls-bin git ca-certificates
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          repository: 'Zaarrg/TTVDropBot'
          path: TTVDropBot
      - name: CD into folder
        run: |
          cd TTVDropBot
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Build
        run: |
          npm install -g pkg
          npm install
          npm run build
          cp ./build/ ../
          cp ./package*.json ../
          cd ..
          npm ci --production
          npm cache clean --force
          npm install
          export NODE_ENV=production
      - name: Package and upload
        uses: lando/pkg-action@v2
        with:
          entrypoint: ./build/index.js
          arch: ${{ matrix.arch }}
          node-version: ${{ matrix.node-version }}
          os: ${{ matrix.os }}
          options: -C GZip
